// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetAnalysisStats() {
  return window['go']['main']['App']['GetAnalysisStats']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function LoadConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadConfig'](arg1, arg2, arg3);
}

export function SaveReport(arg1, arg2) {
  return window['go']['main']['App']['SaveReport'](arg1, arg2);
}

export function SelectConfigFile() {
  return window['go']['main']['App']['SelectConfigFile']();
}

export function StartMonitor(arg1) {
  return window['go']['main']['App']['StartMonitor'](arg1);
}

export function StartSpeedTest(arg1) {
  return window['go']['main']['App']['StartSpeedTest'](arg1);
}

export function StopTest() {
  return window['go']['main']['App']['StopTest']();
}
