// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSystemInfo():Promise<main.SystemInfo>;

export function LoadConfig(arg1:string,arg2:string,arg3:string):Promise<main.ConfigInfo>;

export function SaveReport(arg1:any,arg2:string):Promise<void>;

export function SelectConfigFile():Promise<string>;

export function StartMonitor(arg1:main.MonitorConfig):Promise<void>;

export function StartSpeedTest(arg1:main.TestConfig):Promise<void>;

export function StopTest():Promise<void>;
